version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - /Users/m/Work/Programer/Primelabo/Proas:/var/www/html/
    tty: true
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /Users/m/Work/Programer/Primelabo/Proas:/var/www/html/
    privileged: true
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "33061:3306"

networks:
  frontend:
  backend:
